### ISSUE TITLE
IndexError: index is out of bounds for dimension with size 0

### ISSUE THREAD

**Issue by lif314** [wang-h-w/GraNet#2]
During the training process, an error occurred:
```shell
...
 ---- batch: 8730 ----
...
Warning: N_pos = 0!
Traceback (most recent call last):
  File "train_granet.py", line 250, in <module>
    train(start_epoch)
  File "train_granet.py", line 235, in train
    train_one_epoch()
  File "train_granet.py", line 148, in train_one_epoch
    end_points = net(batch_data_label)
  File "/home/fr3_pc/research/graspnets/GraNet/env_granet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fr3_pc/research/graspnets/GraNet/models/granet_pipeline.py", line 68, in forward
    end_points = self.view_estimator(end_points)
  File "/home/fr3_pc/research/graspnets/GraNet/env_granet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fr3_pc/research/graspnets/GraNet/models/granet_pipeline.py", line 30, in forward
    seed_features, seed_xyz, end_points = self.granet_backbone(graphs, end_points)
  File "/home/fr3_pc/research/graspnets/GraNet/env_granet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fr3_pc/research/graspnets/GraNet/models/graph_learner.py", line 64, in forward
    g_fps, x_fps, x_clone_fps, end_points = self.ops(g, x, x_clone, end_points)
  File "/home/fr3_pc/research/graspnets/GraNet/env_granet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fr3_pc/research/graspnets/GraNet/models/OPS.py", line 106, in forward
    end_points['att1_to_att2_idx'] = idx_mask[idx]
IndexError: index is out of bounds for dimension with size 0
```

**Comment by wang-h-w** [comment]
Thanks for pointing this out. This could be caused by the OPS network predicting all the points of a particular scene as background points during training. I modified the code to address the issue.
