### ISSUE TITLE
请问test时报错ModuleNotFoundError: No module named 'graspnetAPI.utils'怎么解决

### ISSUE THREAD

**Issue by qwertyshen1001** [wang-h-w/GraNet#4]
test时报错，Traceback (most recent call last):
  File "test_granet.py", line 293, in <module>
    evaluate()
  File "test_granet.py", line 135, in evaluate
    res, ap = ge.eval_seen(cfgs.dump_dir, proc=cfgs.num_workers)
  File "/home/GraNet/graspnetAPI/graspnetAPI/graspnet_eval.py", line 249, in eval_seen
    res = np.array(self.parallel_eval_scenes(scene_ids = list(range(100, 130)), dump_folder = dump_folder, proc = proc))
  File "test_granet.py", line 287, in parallel_eval_scenes
    res_list.append(self.eval_scene(scene_id, dump_folder))
  File "test_granet.py", line 173, in eval_scene
    model_list, dexmodel_list, _ = self.get_scene_models(scene_id, ann_id=0)
  File "/home/GraNet/graspnetAPI/graspnetAPI/graspnet_eval.py"", line 53, in get_scene_models
    dexmodel = pickle.load(f)
ModuleNotFoundError: No module named 'graspnetAPI.utils'

**Comment by quanmingxuan** [comment]
你好 可以加个联系方式一起讨论吗

**Comment by qwertyshen1001** [comment]
> 你好 可以加个联系方式一起讨论吗

 请问你解决了吗

**Comment by quanmingxuan** [comment]
你好 还没有解决 这两天不在实验室 明天我再去试一试baseline 我是刚开始复现这个代码 想请问一下baseline的环境配置就是按照作者提供的那样吗 环境配的一塌糊涂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qwertyshen1001 ***@***.***&gt;
发送时间: 2024年5月5日 17:48
收件人: wang-h-w/GraNet ***@***.***&gt;
抄送: quanmingxuan ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [wang-h-w/GraNet] 请问test时报错ModuleNotFoundError: No module named 'graspnetAPI.utils'怎么解决 (Issue #4)





  
你好 可以加个联系方式一起讨论吗
  
请问你解决了吗
